sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: AbmMfu75p+buVQxUFuhWecGlhTKnlwIybDtxIIlRZbbN9nkieSmZuPNdz7FRG2WvSjsfCfDBvJFIN7iPtxXhpCftXGNZnvf/4Ng9/HkBXuoQ2olfG6M9NPP2PF6EIZdBaBfx+jDwCrgVdi1NHlP/02su/OJY8rWYJORanZ/C0mjWdqWkTQjkp8W/G1G54lFSN1zUDFUmTSN+F+9FASf8KsXO9eVf7v2V0An9L/V+TjuyfBiEMlm6/9g+Z1iB2ha9P65owCIHbhDhmABGRxPadnwKQcfSt+QFlgUBhX3SNFuag1SsC4+ML1lLP8ra0B8tP84ef4VmjnS+KTUGHhkDk1MT31NWVjaLsdielSGFT343MOp+edZwM3Azfiv/7gBq2DsCi1UCPPxKySJ9UNMcrIGeLVFuzIXru/01/A504YVBkXY7hWByWA0Yqej4jwlAMEhyusuZq6KfZQbArpa6c6DHERjbVK6dU/NVl8945uTGUwuhQn0D871ZysXgzb5WGRFsXQM77MF7dm0CSSWM9TpA/VUrmerxMCMGi1c5v7OUhJ21eIrtoEQ2ifR0gKgKOf0O7DsVI2Uf7c++YCgFofWg/PVH9+kMUwTXKKo48yp3VtTBCVvoyKCl4Q4SAbHmYGUBOggx1/ZuNMAGRS1jSEMdF29FoiIzKYtlyLAqPRM=
  - secure: DG6bJLAvSb2vD8+gbcrgUkCkd0bm/+4PA5hNND7YzbWZVm9vv0idMzi7ANXB408Yw8AfjWcvO2RghiUiADLvvx7f9fY5qtKP6zF3JdKlO3rg6F0CkgMsSEtYHozEYA/fRJKhKBHKvY9wiKhK9wwhDk23Hwkju+VnzLDH2gp95j9JbgZNl/eTsIGPo4m/qLqoKAfcYD5Nos3SpEc4UKj22OV2lyGQEFuewqFUpWosOz0slKxbdx6NwsIZIDyyKfOBTMIDnVWJ00YSfHhgbE+jZTxTHV5eCpldL+PwQB4cX04oM/SqRkBSr2MOfrtbvufOL4K3OZSXRzg8skuXJNtBgqZXxSM24c37mTRE68GPrnhY8ujrJE4LQrt4DjIUzGYKusBhSQqgJsBQNucAEVx6ISS3E2VPXA/FcfeLAs1MpXtCLrs1kWJ83UY0M9MDeOx/r1ogvbuuGTzYqWKnSZObjLLgVUMiyslfM7O7wE6oX6cpbEgqBg5DueOWyu1RECKASP76p/ohTcZysvxAplnUePs/a+RHX2np32RVRoXhYl1Fy1BMPCqFykMsihKaPSs4NjDZ2ZSDClOAB/fhNvHpBF/aPo7C3QoQbJs+AqC9xu4wAuIcljrkP2L/ETHAEFiiOEXjnvBHKvwm7MWn82JdhZf3Io5x63ue6PrweQwhu2o=
